name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Configure Poetry environment
        run: |
          pip install poetry
          poetry install
      - name: Run tests and coverage
        run: poetry run pytest --cov=yubival --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
